### ISSUE TITLE
@editorjs/underline - Not found in NPM registry

### ISSUE THREAD

**Issue by smajohusic** [editor-js/underline#2]
npm install @editorjs/underline
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@editorjs%2funderline - Not found
npm ERR! 404
npm ERR! 404  '@editorjs/underline@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by neSpecc** [comment]
Fixed
