### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Sozialarchiv** [editor-js/underline#37]
@neSpecc 

The workflow fails because it is using node 16.
https://github.com/editor-js/underline/blob/master/.github/workflows/npm-publish.yml

Other packages have a complete other workflow file:
https://github.com/editor-js/table/blob/master/.github/workflows/npm-publish.yml

Should I use the version from table or should I just update the node version in the current file?

**Comment by neSpecc** [comment]
Its better to use `codex-team/github-workflows/.github/workflows/npm-publish-and-notify-reusable.yml`
